
---
- hosts: all
  tasks:
    - name: Install Apache and ntp
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - httpd
        - ntp
      tags:
        - new_httpd

    - name: Install telnet
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - telnet
        - postfix
      tags:
         - tell_netting

