---
driver:
  name: docker

# Special config for enabling systemd init
default_driver_config: &default_driver_config
  run_command: /sbin/init
  cap_add:
    - SYS_ADMIN
  run_options:
    env: container=docker
  volume:
    - /sys/fs/cgroup:/sys/fs/cgroup
  provision_command:
    - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
    - systemctl enable sshd.service

transport:
  # TODO: remove with better solution than workaround:
  # https://github.com/test-kitchen/test-kitchen/issues/1035
  max_ssh_sessions: 6

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_pip: true
  ansible_version: 2.9.4
  ansible_verbose: true
  ansible_cfg_path: test/ansible.cfg
  requirements_path: test/requirements-test.yml
  idempotency_test: true
  require_chef_for_busser: false
  require_ruby_for_busser: false

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver_config:
      <<: *default_driver_config
    provisioner:
      ansible_cfg_path: test/ansible-legacy.cfg
  - name: fedora-30
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
        - yum -y install python-pip
  - name: fedora-31
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
        - yum -y install python-pip
  - name: ubuntu-16.04
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
  - name: ubuntu-18.04
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
  - name: ubuntu-19.04
    driver_config:
      <<: *default_driver_config
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
  - name: debian-8
    driver_config:
      <<: *default_driver_config
      run_command: /lib/systemd/systemd
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
    provisioner:
      ansible_cfg_path: test/ansible-legacy.cfg
  - name: debian-9
    driver_config:
      <<: *default_driver_config
      run_command: /lib/systemd/systemd
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service

suites:
  - name: install_archive
    provisioner:
      playbook: test/integration/install/install_archive/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/install/install_archive
  - name: install_package
    provisioner:
      playbook: test/integration/install/install_package/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/install/install_package
  - name: config_elasticsearch
    provisioner:
      playbook: test/integration/config/config_elasticsearch/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/config/config_elasticsearch
  - name: jvm_options
    provisioner:
      playbook: test/integration/config/jvm_options/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/config/jvm_options
  - name: log4j2_properties
    provisioner:
      playbook: test/integration/config/log4j2_properties/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/config/log4j2_properties
  - name: launch_service
    provisioner:
      playbook: test/integration/launch/launch_service/default_playbook.yml
    verifier:
      inspec_tests:
        - path: test/integration/launch/launch_service
  - name: uninstall
    provisioner:
      playbook: test/integration/uninstall/default_playbook.yml
      idempotency_test: false
    verifier:
      inspec_tests:
        - path: test/integration/uninstall
