---
- name: Download Elasticsearch package ({{ package_url }})
  become: true
  when: install_type == "package"
  get_url:
    url: "{{ package_url }}"
    dest: "/tmp/{{ package_url | urlsplit('path') | basename }}"
    checksum: "{{ (package_checksum|length > 0) | ternary(checksum_format+':'+package_checksum, '') }}"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_user }}"
    mode: '0775'
  register: package_tmp
  tags:
    - install
    - package

- name: Install Elasticsearch rpm
  become: true
  when: install_type == "package" and ansible_os_family|lower == "redhat"
  yum:
    name: "{{ package_tmp.dest }}"
    state: present
  tags:
    - install
    - package
    - redhat

- name: Install Elasticsearch debian package
  become: true
  when: install_type == "package" and ansible_os_family|lower == "debian"
  apt:
    deb: "{{ package_tmp.dest }}"
    state: present
  tags:
    - install
    - package
    - debian
